$ANSIBLE_VAULT;1.1;AES256
66333031346237336664343933663361663362306362643335613337613765323934653966623861
6533623963623764313932346231363537333961343132340a313533376131333732633365323033
62613930353730363432643762633139333930396230353533643164643561303737333533653731
3232623266393636350a373863323536643935383761316364316161346232626232363337303065
35316661323538316337353831616537363239303266306332336131343132333963646330346332
63613332646530623435346262373338363038633331326434616335393632663736633631363062
34623566356433663133363137393331313466333032386439373334653162643265363135356330
64663561653230626138363537623439393363346539383238363333326635643437313036366462
38613131383536333830633633616439663263323639396534336639613963343331396536373332
30386333616232313231653537333537343435343465656431636535363161396438653330376464
353065383066626637333435363434363464
