$ANSIBLE_VAULT;1.1;AES256
36353939313262376635313235346332323830643462356638373366333038633935373331613035
6338333765663535353333613664396433666462376261660a666661633636323463363136306332
39623464306231633564646237643139333661636433363561326562643734623165383838343231
3662383531633232610a306535623764333839636239373966666463663766333635333361353338
65323637353133343535636531653337306638373031323431663237326631363435653734393238
33636664353061313365656662396232303431373364383264326234316234333738346462396632
38346431633961323033363230386137383861643439653130633262303865343963613262656632
37636663656434343261313462366166363738613337313534663236613664323035626135373261
64336664356665613363346436623763616361613633663065393763626138393333633564363665
34636531663431393839613263636130343433396334303032373931393264393861333864643232
33613264646630383766333364333038306337613935383333393531396261623530373639333835
36313262636434623963333432346661323933353337663538633431386632643039356639303135
35356331353834646566363533303661653134313934373437323236393864633639366462366563
33366530666138626135613363646636346437373363613265363733306136646231633265383364
38356335666365343064623563363531653763363335646266636632653561326233323865666665
36303466353335336439
