$ANSIBLE_VAULT;1.1;AES256
61656534643536653031633561613435396461356435663637323865663332306461363130326436
3330616137633338333133386362643037613530623161340a333430663665643361333564343434
31623331386262313664643432303233386439653038346165303931303639386636393537366137
3561333438363432310a633639373133333039363638336631363736663632616437646537346464
38643866396230326630633862323262326565333239656232393734316333363937323066383234
39313537383738643434663832616635383637366433623537313436613534666166653131303763
34363036326164653061313534346133393834616231633834383139353030316339316565636531
39386661626661626262643466643065366238393562383562313066333261656162343537343330
33626562623932343639386539373337633836316136643432373136363466346330393530373562
65393930356566376163663061626261323963653136626436333337356131336565623337643462
38613632373935623661313230646161643730373663393139393064396162333635366366643437
38366636323434636566306163666235383661356235353937353837333133343437653330656531
39636231633337303836656335633836313765333166383362613064613066653761353762323333
34336263613233316261346334366439303931313236653135656633386230306334376539666465
366463643733313234396161323435393439
